CREATE TABLE [USUARIO] (
  [IDUSER] int PRIMARY KEY NOT NULL IDENTITY(1, 1),
  [TIPOUSER] smallint,
  [NOMBRE] varchar(255),
  [APELLIDO] varchar(255)
)
GO

CREATE TABLE [CATEGORIA] (
  [IDCATEGORIA] int PRIMARY KEY NOT NULL IDENTITY(1, 1),
  [NOMBRECATEGORIA] varchar(255)
)
GO

CREATE TABLE [CURSO] (
  [IDCURSO] int PRIMARY KEY NOT NULL IDENTITY(1, 1),
  [NOMBRECURSO] varchar(255) UNIQUE NOT NULL,
  [IDCATEGORIA] int NOT NULL
)
GO

CREATE TABLE [MODULO] (
  [IDMODULO] int PRIMARY KEY NOT NULL IDENTITY(1, 1),
  [TITULO] varchar(255),
  [IDCURSO] int NOT NULL
)
GO

CREATE TABLE [CLASE] (
  [IDCLASE] int PRIMARY KEY NOT NULL IDENTITY(1, 1),
  [TITULO] varchar(255),
  [IDMODULO] int NOT NULL
)
GO

CREATE TABLE [INSCRIPCION] (
  [NROINSCRIP] int PRIMARY KEY NOT NULL IDENTITY(1, 1),
  [IDUSER] int NOT NULL,
  [IDCURSO] int NOT NULL,
  [FECHAINSCRIP] date
)
GO

CREATE TABLE [EVALUACION] (
  [IDEVAL] int PRIMARY KEY NOT NULL IDENTITY(1, 1),
  [IDUSER] int NOT NULL,
  [IDCLASE] int NOT NULL,
  [CALIFICACIÓN] float,
  [FECHA] datetime
)
GO

CREATE TABLE [PROGRESO] (
  [ID] int PRIMARY KEY NOT NULL IDENTITY(1, 1),
  [IDUSER] int NOT NULL,
  [IDCLASE] int NOT NULL,
  [ESTADO] varchar(20),
  [PORCENTAJE] int
)
GO

CREATE TABLE [PAGO] (
  [ID] int PRIMARY KEY NOT NULL IDENTITY(1, 1),
  [IDUSER] int NOT NULL,
  [IDCURSO] int NOT NULL,
  [FECHA] datetime,
  [MONTO] decimal(10,2),
  [ESTADO] varchar(20)
)
GO

ALTER TABLE [CURSO] ADD FOREIGN KEY ([IDCATEGORIA]) REFERENCES [CATEGORIA] ([IDCATEGORIA])
GO

ALTER TABLE [MODULO] ADD FOREIGN KEY ([IDCURSO]) REFERENCES [CURSO] ([IDCURSO])
GO

ALTER TABLE [CLASE] ADD FOREIGN KEY ([IDMODULO]) REFERENCES [MODULO] ([IDMODULO])
GO

ALTER TABLE [INSCRIPCION] ADD FOREIGN KEY ([IDUSER]) REFERENCES [USUARIO] ([IDUSER])
GO

ALTER TABLE [INSCRIPCION] ADD FOREIGN KEY ([IDCURSO]) REFERENCES [CURSO] ([IDCURSO])
GO

ALTER TABLE [EVALUACION] ADD FOREIGN KEY ([IDUSER]) REFERENCES [USUARIO] ([IDUSER])
GO

ALTER TABLE [EVALUACION] ADD FOREIGN KEY ([IDCLASE]) REFERENCES [CLASE] ([IDCLASE])
GO

ALTER TABLE [PROGRESO] ADD FOREIGN KEY ([IDUSER]) REFERENCES [USUARIO] ([IDUSER])
GO

ALTER TABLE [PROGRESO] ADD FOREIGN KEY ([IDCLASE]) REFERENCES [CLASE] ([IDCLASE])
GO

ALTER TABLE [PAGO] ADD FOREIGN KEY ([IDUSER]) REFERENCES [USUARIO] ([IDUSER])
GO

ALTER TABLE [PAGO] ADD FOREIGN KEY ([IDCURSO]) REFERENCES [CURSO] ([IDCURSO])
GO
