CREATE TABLE `USUARIO` (
  `IDUSER` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `TIPOUSER` smallint,
  `NOMBRE` varchar(255),
  `APELLIDO` varchar(255)
);

CREATE TABLE `CATEGORIA` (
  `IDCATEGORIA` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `NOMBRECATEGORIA` varchar(255)
);

CREATE TABLE `CURSO` (
  `IDCURSO` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `NOMBRECURSO` varchar(255) UNIQUE NOT NULL,
  `IDCATEGORIA` int NOT NULL
);

CREATE TABLE `MODULO` (
  `IDMODULO` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `TITULO` varchar(255),
  `IDCURSO` int NOT NULL
);

CREATE TABLE `CLASE` (
  `IDCLASE` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `TITULO` varchar(255),
  `IDMODULO` int NOT NULL
);

CREATE TABLE `INSCRIPCION` (
  `NROINSCRIP` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `IDUSER` int NOT NULL,
  `IDCURSO` int NOT NULL,
  `FECHAINSCRIP` date
);

CREATE TABLE `EVALUACION` (
  `IDEVAL` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `IDUSER` int NOT NULL,
  `IDCLASE` int NOT NULL,
  `CALIFICACIÓN` float,
  `FECHA` datetime
);

CREATE TABLE `PROGRESO` (
  `ID` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `IDUSER` int NOT NULL,
  `IDCLASE` int NOT NULL,
  `ESTADO` varchar(20),
  `PORCENTAJE` int
);

CREATE TABLE `PAGO` (
  `ID` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `IDUSER` int NOT NULL,
  `IDCURSO` int NOT NULL,
  `FECHA` datetime,
  `MONTO` decimal(10,2),
  `ESTADO` varchar(20)
);

ALTER TABLE `CURSO` ADD FOREIGN KEY (`IDCATEGORIA`) REFERENCES `CATEGORIA` (`IDCATEGORIA`);

ALTER TABLE `MODULO` ADD FOREIGN KEY (`IDCURSO`) REFERENCES `CURSO` (`IDCURSO`);

ALTER TABLE `CLASE` ADD FOREIGN KEY (`IDMODULO`) REFERENCES `MODULO` (`IDMODULO`);

ALTER TABLE `INSCRIPCION` ADD FOREIGN KEY (`IDUSER`) REFERENCES `USUARIO` (`IDUSER`);

ALTER TABLE `INSCRIPCION` ADD FOREIGN KEY (`IDCURSO`) REFERENCES `CURSO` (`IDCURSO`);

ALTER TABLE `EVALUACION` ADD FOREIGN KEY (`IDUSER`) REFERENCES `USUARIO` (`IDUSER`);

ALTER TABLE `EVALUACION` ADD FOREIGN KEY (`IDCLASE`) REFERENCES `CLASE` (`IDCLASE`);

ALTER TABLE `PROGRESO` ADD FOREIGN KEY (`IDUSER`) REFERENCES `USUARIO` (`IDUSER`);

ALTER TABLE `PROGRESO` ADD FOREIGN KEY (`IDCLASE`) REFERENCES `CLASE` (`IDCLASE`);

ALTER TABLE `PAGO` ADD FOREIGN KEY (`IDUSER`) REFERENCES `USUARIO` (`IDUSER`);

ALTER TABLE `PAGO` ADD FOREIGN KEY (`IDCURSO`) REFERENCES `CURSO` (`IDCURSO`);
